languageCode = 'en-us'
title = 'M-Watson'
publishDir = "."
#baseURL = "/"
relativeURLs = true
staticDir = ['style/','img/']
[params]
custom_css = ["style/card-for-no-slides.css",
                        "style/card-for-slides.css",
                        "style/card.css",
                        "style/hovermenu.css",
                        "style/interests.css",
                        "style/navbars.css",
                        "style/style.css"
                      ]
