baseURL = 'm-watson.github.io'
languageCode = 'en-us'
title = 'M-Watson'
publishDir = "."
[params]
custom_css = ["style/card-for-no-slides.css",
                        "style/card-for-slides.css",
                        "style/card.css",
                        "style/hovermenu.css",
                        "style/interests.css",
                        "style/navbars.css",
                        "style/style.css"
                      ]
