languageCode = 'en-us'
title = 'M-Watson'
publishDir = "."
staticDir = ['static/img','static/style']
[params]
custom_css = ["style/card-for-no-slides.css",
                        "style/card-for-slides.css",
                        "style/card.css",
                        "style/hovermenu.css",
                        "style/interests.css",
                        "style/navbars.css",
                        "style/style.css"
                      ]
