baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "ananke"

[params]
custom_css = ["style/card-for-no-slides.css",
                        "style/card-for-slides.css",
                        "style/card.css",
                        "style/hovermenu.css",
                        "style/interests.css",
                        "style/navbars.css",
                        "style/style.css"
                      ]
